name: Build and Deploy Docker Services

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add remote server to known_hosts
        run: |
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'ENDSSH'
            # Check if ComplexHelloWorld directory exists, if not clone it
            if [ ! -d ~/ComplexHelloWorld ]; then
              echo "Directory not found. Cloning repository..."
              git clone ${{ github.server_url }}/${{ github.repository }}.git ~/ComplexHelloWorld
            fi

            # Navigate to project directory
            cd ~/ComplexHelloWorld

            # Pull latest code
            git pull

            # Build and restart services using docker-compose
            docker compose up -d
          ENDSSH
      
