name: Build and Deploy Docker Services

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add remote server to known_hosts
        run: |
          ssh-keyscan ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
          
      - name: Deploy to server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'ENDSSH'
            # Navigate to project directory
            cd ${{ secrets.PROJECT_DIR }}
            
            # Pull latest code
            git pull
            
            # Build and restart services using docker-compose
            docker compose build
            docker compose up -d
          ENDSSH
